### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by alexmerlin** [birkof/netopia-mobilpay-bundle#7]
@birkof First of all, great job on bringing this library to the 21st century... MobilPay's version is way too outdated.

Before diving into my issue, I can confirm that the library is correctly installed and configured (signature, public cert and private key are all in their place) because I'm able to encrypt the data required by the payment form, submit it, fill in the test card details and I do receive MobilPay's call to the confirmUrl.

My issue is that I can't decrypt the response coming from MobilPay - as it keeps throwing `Failed decrypting data`.
Even tried creating a payment object and try to decrypt it, but the result is the same error.

```
// create payment object - works
$payment = $this->mobilPayService->createCreditCardPaymentObject(
    $order->getId(),
    $order->getListTotal(),
    NetopiaMobilPayConfiguration::CURRENCY_RON,
    'Comanda de Test',
    $order->getBillingAddress()->toMobilPayArray(),
    $order->getShippingAddress()->toMobilPayArray()
);

// try to decrypt it - fails
$response = RequestAbstract::factoryFromEncrypted(
    $payment->getEnvKey(),
    $payment->getEncData(),
    $this->mobilPayService->getMobilPayConfiguration()->getPrivateKey()
);
dd($response);
```

Could you advise on what could be wrong?

**Comment by birkof** [comment]
Hey @alexmerlin,
Thank you for your kind words!

[Here](https://github.com/birkof/netopia-mobilpay-bundle/issues/2#issuecomment-499794203), you'll find a working example with this library.

**Comment by alexmerlin** [comment]
Yes, I've seen that example before opening this issue.
I'm doing exactly the same thing, calling `RequestAbstract::factoryFromEncrypted` when I get the `Failed decrypting data` error.
The error is not in your library, I just thought maybe you have a clue on why would the decryption fail.

**Comment by birkof** [comment]
The `EnvKey` and `EncData` variables are the ones received from Netopia?

**Comment by alexmerlin** [comment]
Yes, they are.
As a doublecheck I also tried decrypting a payment object I've created using createCreditCardPaymentObject but that also fails with the same error.
I've looked up the error all over but couldn't find anything related to this, that's why I thought I'd ask here.

**Comment by birkof** [comment]
I have no other clue here. IMHO it should be a misconfiguration on your side. Check 'em twice.
Also, are you working on sandboxed mode?

**Comment by alexmerlin** [comment]
Yes, I'm on sandbox.
I'll check again and will find the issue. If it's something that could be useful to future devs, I'll leave a comment with my findings.
Thanks for your attention and the prompt answers. :)

**Comment by alexmerlin** [comment]
My bad! I was using the live environment's private key to decrypt a message encrypted with the sandbox key.
